pipeline {
    agent any

    environment {
        PROJECT_ID = "your-gcp-project-id"
        REGION     = "us-central1"
        REPO       = "devops-repo"
        IMAGE      = "gcp-devops-app"
        TAG        = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/your-username/gcp-devops-ci-cd.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE:$TAG .'
            }
        }

        stage('Push Image to Artifact Registry') {
            steps {
                sh '''
                docker tag $IMAGE:$TAG $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$TAG
                docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$TAG
                '''
            }
        }

        stage('Deploy to GKE') {
            steps {
                sh '''
                kubectl apply -f k8s/
                '''
            }
        }
    }
}
