# =========================
# 1️⃣ DEPLOYMENT
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp-devops-app
  template:
    metadata:
      labels:
        app: gcp-devops-app
    spec:
      containers:
      - name: app
        image: nginx:latest   # safe public image
        ports:
        - containerPort: 80

---
# =========================
# 2️⃣ SERVICE
# =========================
apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-service
spec:
  type: NodePort
  selector:
    app: gcp-devops-app
  ports:
  - port: 80
    targetPort: 80

---
# =========================
# 3️⃣ INGRESS
# =========================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gcp-devops-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gcp-devops-service
            port:
              number: 80
